kotlin.code.style=official
kotlinVersion=2.1.0
composeVersion=1.8.0
junitVersion=5.10.2
kotlinLoggingVersion=7.0.13
logbackVersion=1.5.3
slf4jVersion=2.0.12
hikariVersion=5.1.0
exposedVersion=0.50.0
flywayVersion=10.10.0
postgresVersion=42.7.3
coroutinesVersion=1.8.1
jgitVersion=6.9.0.202403050737-r
mockkVersion=1.13.11
serializationVersion=1.7.1
ktorVersion=2.3.12

org.gradle.jvmargs=-Xmx2g -XX:MaxMetaspaceSize=512m
org.gradle.parallel=true
org.gradle.caching=true

