package com.aitask.core.infrastructure.rules

import com.aitask.core.domain.model.IDEType
import com.aitask.core.domain.model.Rule
import com.aitask.core.domain.model.RuleCategory
import com.aitask.core.domain.service.RuleApplicationResult
import com.aitask.core.domain.service.RuleApplicationService
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import java.io.File

/**
 * File system implementation of RuleApplicationService
 * Writes rules to workspace in IDE-compatible formats
 */
class FileSystemRuleApplicationService : RuleApplicationService {
    
    override suspend fun applyRulesToWorkspace(
        workspacePath: String,
        rules: List<Rule>,
        ideType: IDEType?
    ): Result<RuleApplicationResult> = withContext(Dispatchers.IO) {
        try {
            val filesCreated = mutableListOf<String>()
            
            // Group rules by category
            val rulesByCategory = rules.groupBy { it.category }
            
            // Determine rule directory based on IDE type
            val ruleDir = getRuleDirectory(workspacePath, ideType)
            val ruleDirFile = File(ruleDir)
            
            // Create rule directory if it doesn't exist
            if (!ruleDirFile.exists()) {
                ruleDirFile.mkdirs()
            }
            
            // Write rules by category
            for ((category, categoryRules) in rulesByCategory) {
                val fileName = getCategoryFileName(category)
                val filePath = File(ruleDir, fileName)
                
                val content = buildRuleFileContent(categoryRules, category, ideType)
                filePath.writeText(content)
                filesCreated.add(filePath.absolutePath)
            }
            
            // If there are uncategorized rules, write them to a general file
            val uncategorizedRules = rulesByCategory[null]
            if (!uncategorizedRules.isNullOrEmpty()) {
                val filePath = File(ruleDir, "general-rules.md")
                val content = buildRuleFileContent(uncategorizedRules, null, ideType)
                filePath.writeText(content)
                filesCreated.add(filePath.absolutePath)
            }
            
            Result.success(
                RuleApplicationResult(
                    filesCreated = filesCreated,
                    rulesApplied = rules.size,
                    success = true
                )
            )
        } catch (e: Exception) {
            Result.failure(Exception("Failed to apply rules to workspace: ${e.message}", e))
        }
    }
    
    override fun getRuleFilePath(workspacePath: String, ideType: IDEType?): String {
        return getRuleDirectory(workspacePath, ideType)
    }
    
    override suspend fun validateWorkspace(workspacePath: String): Boolean = withContext(Dispatchers.IO) {
        try {
            val workspaceDir = File(workspacePath)
            workspaceDir.exists() && workspaceDir.isDirectory
        } catch (e: Exception) {
            false
        }
    }
    
    /**
     * Get the rule directory path based on IDE type
     */
    private fun getRuleDirectory(workspacePath: String, ideType: IDEType?): String {
        return when (ideType) {
            IDEType.CURSOR -> "$workspacePath/.cursor/rules"
            IDEType.VS_CODE -> "$workspacePath/.vscode/rules"
            IDEType.INTELLIJ_IDEA, IDEType.PYCHARM, IDEType.WEBSTORM, IDEType.GOLAND -> 
                "$workspacePath/.idea/rules"
            else -> "$workspacePath/.aitask/rules"
        }
    }
    
    /**
     * Get the file name for a rule category
     */
    private fun getCategoryFileName(category: RuleCategory?): String {
        return when (category) {
            RuleCategory.CODING_STANDARDS -> "coding-standards.md"
            RuleCategory.ARCHITECTURE -> "architecture.md"
            RuleCategory.TESTING -> "testing.md"
            RuleCategory.DOCUMENTATION -> "documentation.md"
            RuleCategory.AI_ASSISTANT -> "ai-assistant.md"
            null -> "general-rules.md"
        }
    }
    
    /**
     * Build the content for a rule file
     */
    private fun buildRuleFileContent(
        rules: List<Rule>,
        category: RuleCategory?,
        ideType: IDEType?
    ): String = buildString {
        // Header
        val categoryName = category?.name?.replace('_', ' ')?.lowercase()
            ?.replaceFirstChar { it.uppercase() } ?: "General Rules"
        
        appendLine("# $categoryName")
        appendLine()
        appendLine("Generated by AiTask on ${java.time.Instant.now()}")
        if (ideType != null) {
            appendLine("IDE: ${ideType.name}")
        }
        appendLine()
        appendLine("---")
        appendLine()
        
        // Rules
        for (rule in rules) {
            appendLine("## ${rule.name}")
            appendLine()
            appendLine(rule.content)
            appendLine()
            appendLine("---")
            appendLine()
        }
    }
}

